local M = {}

local group = vim.api.nvim_create_augroup('custom-cern-root', { clear = true })

local function rootls(target, flags)
  if vim.fn.executable 'rootls' == 0 then
    return {
      'rootls was not found in PATH.',
      'Install CERN ROOT or open the file in a terminal with ROOT available.',
    }, 127
  end

  local cmd = { 'rootls' }
  vim.list_extend(cmd, flags or {})
  table.insert(cmd, target)

  local lines = vim.fn.systemlist(cmd)
  local code = vim.v.shell_error

  if #lines == 0 then
    lines = { '(no ROOT objects listed)' }
  end

  return lines, code
end

local function root_file_from_target(target)
  if target == nil or target == '' then
    return nil
  end

  local root_file = target:match '^(.-%.root):.*$' or target
  return vim.fn.fnamemodify(root_file, ':p')
end

local function current_root_target()
  if vim.b.cern_root_file ~= nil and vim.b.cern_root_file ~= '' then
    return vim.b.cern_root_file
  end

  local name = vim.api.nvim_buf_get_name(0)
  if name:match '%.root$' then
    return name
  end
end

local function current_root_file()
  return root_file_from_target(current_root_target())
end

local function notify_missing_target(usage)
  vim.notify('Usage: ' .. usage .. ' [file.root]', vim.log.levels.WARN)
end

local function start_detached(cmd, missing_executable_message)
  if vim.fn.executable(cmd[1]) == 0 then
    vim.notify(missing_executable_message, vim.log.levels.ERROR)
    return
  end

  local job_id = vim.fn.jobstart(cmd, {
    detach = true,
    cwd = vim.fn.getcwd(),
  })

  if job_id <= 0 then
    vim.notify('Failed to start: ' .. table.concat(cmd, ' '), vim.log.levels.ERROR)
    return
  end

  vim.notify('Started: ' .. table.concat(cmd, ' '))
end

local function set_root_buffer(bufnr, target, lines)
  vim.bo[bufnr].buftype = 'nowrite'
  vim.bo[bufnr].swapfile = false
  vim.bo[bufnr].modifiable = true
  vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, lines)
  vim.bo[bufnr].filetype = 'root'
  vim.b[bufnr].cern_root_file = target
  vim.bo[bufnr].modified = false
  vim.bo[bufnr].readonly = true
  vim.bo[bufnr].modifiable = false
end

local function build_listing(target)
  local lines, code = rootls(target, { '-t', '-r' })
  local header = {
    'ROOT file: ' .. target,
    'Generated by: rootls -t -r',
    '',
  }

  vim.list_extend(header, lines)

  if code ~= 0 then
    table.insert(header, 1, 'rootls exited with code ' .. tostring(code))
    table.insert(header, 2, '')
  end

  return header
end

local function open_scratch(name, lines, target)
  local bufnr = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_name(bufnr, name)
  vim.api.nvim_set_current_buf(bufnr)
  set_root_buffer(bufnr, target, lines)
  vim.bo[bufnr].bufhidden = 'wipe'
end

function M.open_file(path, bufnr)
  local target = vim.fn.fnamemodify(path, ':p')
  set_root_buffer(bufnr, target, build_listing(target))
end

function M.refresh()
  local target = current_root_target()
  if target == nil then
    vim.notify('No ROOT file associated with this buffer', vim.log.levels.WARN)
    return
  end

  set_root_buffer(0, target, build_listing(target))
end

function M.list(target)
  target = target ~= nil and target ~= '' and target or current_root_target()
  if target == nil then
    vim.notify('Usage: :RootLs [file.root[:path]]', vim.log.levels.WARN)
    return
  end

  open_scratch('ROOT listing: ' .. target, build_listing(target), target)
end

function M.keys(target)
  target = target ~= nil and target ~= '' and target or current_root_target()
  if target == nil then
    vim.notify('Usage: :RootKeys [file.root[:path]]', vim.log.levels.WARN)
    return
  end

  local lines = rootls(target, { '-1' })
  open_scratch('ROOT keys: ' .. target, lines, target)
end

function M.browse(target, opts)
  opts = opts or {}
  target = root_file_from_target(target ~= nil and target ~= '' and target or current_root_file())
  if target == nil then
    notify_missing_target ':RootBrowse'
    return
  end

  local cmd = { 'rootbrowse' }
  if opts.classic then
    table.insert(cmd, '-wf')
  elseif opts.web_display ~= nil and opts.web_display ~= '' then
    vim.list_extend(cmd, { '-w', opts.web_display })
  end
  table.insert(cmd, target)

  start_detached(cmd, 'rootbrowse was not found in PATH')
end

function M.console(target)
  target = root_file_from_target(target ~= nil and target ~= '' and target or current_root_file())
  if target == nil then
    notify_missing_target ':RootConsole'
    return
  end

  if vim.fn.executable 'root' == 0 then
    vim.notify('root was not found in PATH', vim.log.levels.ERROR)
    return
  end

  local ok, terminal = pcall(require, 'toggleterm.terminal')
  if ok then
    terminal.Terminal:new({
      cmd = 'root -l ' .. vim.fn.shellescape(target),
      dir = vim.fn.fnamemodify(target, ':h'),
      direction = 'float',
      close_on_exit = false,
    }):toggle()
    return
  end

  vim.cmd 'botright split'
  vim.fn.termopen({ 'root', '-l', target }, {
    cwd = vim.fn.fnamemodify(target, ':h'),
  })
  vim.cmd 'startinsert'
end

local function root_web_command(opts)
  local args = vim.deepcopy(opts.fargs)
  local web_display = nil
  local target = nil

  if #args == 1 then
    if args[1]:match '%.root' then
      target = args[1]
    else
      web_display = args[1]
    end
  elseif #args >= 2 then
    web_display = args[1]
    target = args[2]
  end

  M.browse(target, { web_display = web_display })
end

vim.api.nvim_create_autocmd('BufReadCmd', {
  group = group,
  pattern = '*.root',
  callback = function(event)
    M.open_file(event.file, event.buf)
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  group = group,
  pattern = 'root',
  callback = function(event)
    vim.keymap.set('n', '<leader>rb', function()
      M.browse()
    end, { buffer = event.buf, desc = '[R]OOT [b]rowse' })

    vim.keymap.set('n', '<leader>rB', function()
      M.browse(nil, { classic = true })
    end, { buffer = event.buf, desc = '[R]OOT classic [B]rowser' })

    vim.keymap.set('n', '<leader>rc', function()
      M.console()
    end, { buffer = event.buf, desc = '[R]OOT [c]onsole' })

    vim.keymap.set('n', '<leader>rr', M.refresh, { buffer = event.buf, desc = '[R]OOT [r]efresh' })
  end,
})

vim.api.nvim_create_user_command('RootLs', function(opts)
  M.list(opts.args)
end, {
  nargs = '?',
  complete = 'file',
  desc = 'Open a recursive CERN ROOT file listing',
})

vim.api.nvim_create_user_command('RootKeys', function(opts)
  M.keys(opts.args)
end, {
  nargs = '?',
  complete = 'file',
  desc = 'Open top-level CERN ROOT keys',
})

vim.api.nvim_create_user_command('RootBrowse', function(opts)
  M.browse(opts.args, { classic = opts.bang })
end, {
  bang = true,
  nargs = '?',
  complete = 'file',
  desc = 'Open a CERN ROOT file with rootbrowse; bang uses classic TBrowser',
})

vim.api.nvim_create_user_command('RootBrowseClassic', function(opts)
  M.browse(opts.args, { classic = true })
end, {
  nargs = '?',
  complete = 'file',
  desc = 'Open a CERN ROOT file with the classic TBrowser',
})

vim.api.nvim_create_user_command('RootBrowseWeb', root_web_command, {
  nargs = '*',
  complete = 'file',
  desc = 'Open a CERN ROOT file with rootbrowse -w [webdisplay]',
})

vim.api.nvim_create_user_command('RootConsole', function(opts)
  M.console(opts.args)
end, {
  nargs = '?',
  complete = 'file',
  desc = 'Open a ROOT console for a CERN ROOT file',
})

vim.api.nvim_create_user_command('RootRefresh', M.refresh, {
  desc = 'Refresh the current CERN ROOT listing',
})

return M
